#%RAML 1.0 Extension
title: ApiExtension

# The contents of the file after removal of the RAML fragment identifier
# line MUST be valid structurally according to the relevant RAML
# specification.

baseUri: http://myItems.com
extends: main.raml
uses:
  decls:  lib/decls.raml
/items:
  get:
    description: |
      describing your method here
    #lets add some annotation
    (decls.important):
hi: 1