#%RAML 1.0 Extension
title: ApiExtension
baseUri: http://myItems.com
extends: master.raml
uses:
  decls:  lib/decls.raml
types:
  File:
    properties:
      name:
      length:
        type: integer
traits:
  drm:
    headers:
      drm-key:
resourceTypes:
  file:
    get:
      is: [ drm ]
    put:
      is: [ drm ]
securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication
annotationTypes:
  suborg:
    type: object
    properties:
      prop1?: number
      /.*/: object
securedBy: [ basic ]
/items:
  get:
    description: |
      describing your method here
    #lets add some annotation
    (decls.important):
