#%RAML 1.0
title: API

traits:
  trait1:
    queryParameters:
      param1: string

types:
  User:
    properties:
      name: string
      age: number

resourceTypes:
  SomeType:
    get:
      is: [trait989898]
      responses:
        200:
          body:
            application/json:
              type: User

  AnotherType:
    type: SomeType
    put:
      body:
        application/json:
          type: User

/resource:
  type: AnotherType
