#%RAML 1.0
title: Invalid Discriminator Usage

types:
  Person:
  Dog:
  PersonOrDog:
    type: Person | Dog
    discriminator: hasTail # not allowed

/inline:
  get:
    responses:
      200:
        body:
          application/json:
            discriminator: kind # not allowed
            properties:
              kind: string
