#%RAML 1.0
title: API

baseUri: /some/base/uri

/someUri:
  get:
    responses:
      200:
        body:
          application/json:
             discriminator: kind
             properties:
               kind: string
