#%RAML 1.0
title: Version Manager

# https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#includes
# absolute path     A path that begins with a single slash (/) and is
# interpreted relative to the root RAML file location.
#
# No invalid test case because it's impossible to test invalid case without
# system preparation.

types:
  Release: !include /dataTypes/Release.raml

resourceTypes:
  member: !include /resourceTypes/member.raml

/release:
  type: member
  get: