#%RAML 1.0 DataType

# The contents of the file after removal of the RAML fragment identifier
# line MUST be valid structurally according to the relevant RAML
# specification.

uses:
  lib: lib/lib.raml
properties:
  prop1: number
  prop2: lib.ObjectType
hi: 1