#%RAML 1.0 Library

# Objective: The following example shows a simple library as a standalone, reusable RAML fragment document.
# Expected result: no error message
# The contents of the file after removal of the RAML fragment identifier
# line MUST be valid structurally according to the relevant RAML
# specification.

# tags: library

usage: |
  Use to define some basic file-related constructs.
types:
  File:
    properties:
      name:
      length:
        type: integer
traits:
  drm:
    headers:
      drm-key:
resourceTypes:
  file:
    get:
      is: [ drm ]
    put:
      is: [ drm ]
hi: 1
