#%RAML 1.0
title: Illustrating allowed targets
mediaType: application/json

annotationTypes:
  test:
    allowedTargets: ResponseBody

(test): hi

/users:
  get:
    responses:
      200:
        application/json:
