#%RAML 1.0
title: Illustrating allowed targets
mediaType: application/json
documentation:
  - title: title
    (test): hi
    content: hello

annotationTypes:
  test:
    allowedTargets: DocumentationItem
