#%RAML 1.0
title: test
/test:
  post:
    queryString:
      type: string
    queryParameters:
      status:
        description: The status.
        required: true
        enum:
          - accepted
          - rejected
          - pending
    body:
      application/json:
    responses:
      201: