# https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#includes
# relative path   A path that neither begins with a single slash (/) nor
# constitutes a URL, and is interpreted relative to the location of the
# included file.

#%RAML 1.0 ResourceType

uses:
  traitsLibrary: ../libraries/TraitsLibrary.raml
get?:
  is:
    - traitsLibrary.hasGetResResponse