#%RAML 1.0
title: GitHub API
version: v3
baseUri: https://api.github.com
documentation:
 - title: Getting Started
   content: !include resources/docs/legal.markdown
 - title: Basics of Authentication
   content: !include resources/docs/relative.md