#%RAML 0.8

# A method can override an API's protocols value for that single method by setting a different value for the fields.
# In the following example, the GET method is accessible through both HTTP and HTTPS, while the rest of
# the API only through HTTPS.

title: Twitter API
version: 1.1
baseUri: https://api.twitter.com/{version}
/search/tweets.json:
  displayName: Tweet Search
  get:
    description: Returns a collection of relevant Tweets matching a specified query
    protocols: [HTTP, HTTPS]