#%RAML 1.0

# Objective: The following example shows a RAML fragment file that defines a resource type and a file that includes this fragment file.
# Expected result: no error message

# tags: include

title: Example API
version: v1
resourceTypes: !include resources/patterns/resourceTypes_Rv1-0.yaml
traits: !include resources/patterns/traits_Rv1-0.yaml
