#%RAML 0.8
baseUri: https://api.example.com
title: Filesystem API
version: 0.1
schemas:
  - !include    .resources/schemas/schemas.raml
  - Group:      !include .resources/schemas/group.xsd
  - Invoice:    !include .resources/schemas/invoice.xsd
/files:
  get:
    responses:
      200:
        body:
          application/xml:
            schema: Invoice