#%RAML 0.8

# For APIs without a priori knowledge of the response types for their responses, "*/*" MAY be used to indicate that
# responses that do not match other defined data types MUST be accepted. Processing applications MUST match the most
# descriptive media type first if "*/*" is used.

title: title

/media/{mediaid}/content:
  displayName: Content
  get:
    description: |
      Get a media file.
    responses:
      200:
        body:
          "*/*":