#%RAML 1.0
title: test

# Processors MUST treat these numeric keys as string keys in all situations.
# For example, '200' and 200 MUST be treated as duplicate keys, and therefore,
# are not allowed simultaneously.

/test:
  get:
    responses:
      200:
      '200':