#%RAML 1.0
title: Example of Optional Properties
resourceTypes:
  corpResource:
    hello?:
      description: Some info about <<TextAboutPost>>.
      headers:
        X-Chargeback:
          required: true
/servers:
  type:
    corpResource:
      TextAboutPost: post method
  get:
  post:
/queues:
  type: corpResource
  get:
