#%RAML 1.0
title: A

resourceTypes:
  b:
    get:
      responses: 
        200:
          body: 
            application/json:
              example: <<c>>
      
/a:
  type:
    b: 
      c: !include includes/example_Rv1-0.raml