#%RAML 1.0
title: Test

# a root RAML document must be valid when it references a valid type
# from a library even when the library contains validation errors

uses:
  bar: libs/bar-lib-unknown-type-invalid.raml

/foo:
  get:
    description: Returns a list of Jira Issues
    responses:
      200:
        body:
          application/json:
            type: bar.A