#%RAML 1.0
title: Test

# a root RAML document must not be valid when it references an
# invalid type from a library

uses:
  bar: libs/bar-lib-unknown-type-invalid.raml

/foo:
  get:
    description: Returns a list of Jira Issues
    responses:
      200:
        body:
          application/json:
            type: bar.B