#%RAML 1.0
title: test

types:
  TestType:
    type: object
    properties:
      name: string
    examples:
      first:
        strict: true
        name: 1
      second:
        strict: false
        name: 2
