#%RAML 1.0

title: My API title

# https://github.com/raml-org/raml-java-parser/issues/233

types:
  Pet:
    properties:
      name: string
      cost: number
  Dog:
    type: Pet
    properties:
      cost: integer
