#%RAML 1.0 Overlay
title: Slave RAML
extends: base.raml
uses:
  decls: lib/decls.raml

/elements:
  get:
    description: |
      describing your method here
    (decls.important):

protocols: [HTTPS]