#%RAML 1.0
title: test
types:
  TestType:
      type: object
      properties:
        field: string
      example:
        field: value
  TestType3:
      type: TestType2
/test:
  get:
    responses:
      200: