#%RAML 0.8

# API's may include the the placeholder token {?} in a header name to indicate that any number of headers that
# conform to the specified format can be sent in responses. This is particularly useful for APIs that allow
# HTTP headers that conform to some naming convention to send arbitrary, custom data.
# In the following example, the header x-metadata-{?} is used to send metadata that has been saved with the media.

title: title
/media/popular:
  displayName: Most Popular Media
  get:
    description: |
      Get a list of what media is most popular at the moment.
    responses:
      200:
        description: |
          The list of popular media.
        headers:
          x-meta-{?}:
            description: |
              Field names prefixed with x-meta- contain user-specified metadata.