# https://github.com/raml-org/raml-java-parser/issues/172

#%RAML 1.0
title: Dropbox API
version: 1
baseUri: https://api.dropbox.com/{version}
securitySchemes:
  oauth_1_0:
    description: |
      Dropbox supports OAuth 1.0 for authenticating all API requests.
    type: OAuth 1.0
    settings:
      requestTokenUri: https://api.mysampleapi.com/1/oauth/request_token
      tokenCredentialsUri: https://api.mysampleapi.com/1/oauth/access_token
      authorizationUri: https://api.mysampleapi.com/1/oauth/authorize
      signatures: [ 'HMAC-SHA1', 'PLAINTEXT' ]
