# Moreover, if additionalProperties is false (explicitly or by inheritance)
# in a given type definition, then explicitly setting pattern properties in
# that definition is not allowed.

#%RAML 1.0
title: My API With Types
types:
  Method:
    type: object
    properties:
      name:
        type: string
  Resource:
    type: object
    additionalProperties: false
    properties:
      /post|get|put/: Method
    example:
      put:
        name: update method
      post:
        name: create method
