#%RAML 1.0 Overlay
title: Pet Shop Overlay
extends: base.raml

/resource:
  get:
    responses:
      201:
        body:
          application/json:
            examples:
              test:
                value:
                  name: 7
