#%RAML 1.0
title: API

types:
  SomeType:
    displayName: Some cool type
    description: Some cool type description
    type: object
    properties:
      name: string
    example:
      name: somestring
