#%RAML 1.0
title: Title

# https://github.com/raml-org/raml-js-parser-2/issues/798

version: 1.0

uses:
  query: lib.raml

/accou:
  get:
    queryString:
      type: query.query
    responses:
      200:
        body:
          application/json:
