#%RAML 1.0
title: A title

# https://github.com/raml-org/raml-js-parser-2/issues/753

resourceTypes:
  collection: !include resourceTypes/collection.raml

/testURI:
  type:
    collection:
      postRequestBodyExample: !include examples/example.raml