#%RAML 1.0
title: type example

# https://github.com/raml-org/raml-js-parser-2/issues/776

version: 1

types:
  ResourceLink:
    description: a description
    facets:
      a: string
      b: number
    properties:
      href: string
      rel:
        enum: [self, next, prev]
      method:
        default: get
        required: false
  ImageLink:
    properties:
      href: string
      rel:
        enum: [SmallImage, MediumImage, LargeImage]
