#%RAML 1.0
title: Valid use of JSON schema as a type definition using short form

types:
  Person: |
    {
      "$schema": "http://json-schema.org/draft-03/schema",
      "properties": {
        "input": {
          "required": false,
          "type": "string"
        }
      },
      "required": false,
      "type": "object"
