# https://github.com/raml-org/raml-js-parser-2/issues/785

#%RAML 1.0
title: Some API
version: v1
mediaType:  application/json
baseUri: https://example.com/api/v1/

securitySchemes:
  hmac: !include securitySchemes/hmac.raml