#%RAML 1.0
title: Illustrating annotations
mediaType: application/json

annotationTypes:
  clearanceLevel: !include includes/valid-annotation.raml

/groups:
  (clearanceLevel):
    level: high
    signature: 230-ghtwvfrs1itr
