#%RAML 1.0
title: API with Types
types:
  Thing:
    type: object
    properties:
      test: nil
    example:
      test: "null"

/things/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Thing
