#%RAML 1.0
title: API with Types
types:
  Thing:
    type: object
    properties:
      one: any
      two: array
      three: number
      four: integer
      five: boolean
      six: nil
    example:
      one: "hi"
      two: "[1, 2, 3]"
      three: 18.2
      four: 19
      five: true
      six: null

/things/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Thing
