#%RAML 0.8

# Objective: The following example shows a RAML fragment file that defines a resource type and a file that includes this fragment file.
# Expected result: no error message

# tags: include
---
title: Example API

version: v1
resourceTypes: !include resources/patterns/resourceTypes.raml # where resourceTypes.raml is an array of maps of resource type definitions
traits: !include resources/patterns/traits.raml  # where traits.raml is an array of maps of trait definitions