#%RAML 1.0
title: API
version: v1
resourceTypes:
  type1:
    get:
      responses:
        200:
          description: ok (from resource type "type 1")
/users:
  type: [type1]
  get:
    description: "GET users"