# The contents of the file after removal of the RAML fragment identifier
# line MUST be valid structurally according to the relevant RAML
# specification.

#%RAML 1.0 DataType
properties:
  first : string
  second: string
hi: 1