# The !include tag argument must be static: namely, it MUST NOT contain
# any resource type parameters or trait parameters.

#%RAML 1.0
title: Test API

resourceTypes:
  myResource: !include <<version>>.raml
