#%RAML 1.0
title: test API

# https://github.com/raml-org/raml-js-parser-2/issues/718

/resource:
  get:
    responses:
      200:
        body:
          application/json:
            example: !includeexample.json
