#%RAML 1.0
title: Resources with query parameters

# https://github.com/raml-org/raml-java-parser/issues/240

/invalid/{first}:
  uriParameters:
    first:
      examples:
        whatever: "invalid/value"
