#%RAML 1.0

title: properties with trailing question marks
types:
  Person:
    type: object
    properties:
      name: string
      title??:
        type: string
        required: true
    example:
      name: eleo
