#%RAML 1.0
title: Illustrate query parameter variations

types:
  lat-long:
    properties:
      lat: number
      long: number
  loc:
    properties:
      location:
  paging:
    properties:
      start?: number
      page-size?: number

/locations:
  get:
    queryString:
      type: [paging,  lat-long | loc ]
      examples: !include examples/valid-multiple-examples.raml
