# https://github.com/raml-org/raml-js-parser-2/issues/819

#%RAML 1.0
title: Edge case demo

types:
  type1: [string, number]
  type2: [number, integer]
  type3: [integer, boolean]
  type4: [date, boolean]
  type5: [date, file]
