#%RAML 1.0
title: Test API

# https://github.com/raml-org/raml-java-parser/issues/221

types:
  orders:
    properties:
      Priority:
        type: number
        format: int16
/resource:
  post:
    body:
      application/json:
        type: orders
        example:
          Priority: 3
