# https://github.com/raml-org/raml-js-parser-2/issues/777

#%RAML 1.0 DataType

displayName: File
description: The File resource type.
type: !include resource.raml

properties:
  thumbnail:
    type: !include thumbnail.raml
    required: false