#%RAML 1.0
title: test
types:
  TestType:
      type: object
      properties:
        field: string
      example:
        field: value
/test:
  post:
    body:
      application/json:
        type: TestType
        scheme: ""
    responses:
      201:
        body:
          application/json:
            type: TestType
            scheme: ""