#%RAML 1.0
title: API
resourceTypes:
  thingy:
    get:
      responses:
        200:
          body:
            <<mediaType>>:
              type: file
/books:
  type:
    thingy:
      mediaType: qweqweqweqwe
