#%RAML 1.0
title: API

# https://github.com/raml-org/raml-js-parser-2/issues/760

resourceTypes:
  thingy:
    get:
      responses:
        200:
          body:
            <<mediaType>>:
              type: file
/books:
  type:
    thingy:
      mediaType: application/json
