#%RAML 1.0 ResourceType

# The contents of the file after removal of the RAML fragment identifier
# line MUST be valid structurally according to the relevant RAML
# specification.

description: A collection resource
usage: Use this to describe a resource that lists items
get:
  description: Retrieve all items
post:
  description: Add an item
  responses:
    201:
      headers:
        Location:
hi: 1