# If two or more pattern property regular expressions match a
# property name in an instance of the data type, the first one prevails.

#%RAML 1.0
title: My API With Types
types:
  Method:
    type: object
    properties:
      name:
        type: string
  Resource:
    type: object
    properties:
      /post|get|put/:
        type: Method
      //:
        type: number
    example:
      put:
        name: update method
      post:
        name: create method