#%RAML 1.0 Library
usage: Gmail types
types:
  Header:
    type: object
    properties:
      name: string
      value: string
  Message:
    type: object
    properties:
      id?: string

      payload?:
        type: object
        properties:
          mimeType?: string
          filename?: string
          headers: Header[]
          body?:
            type: object
            properties:
              size?: number
              data?: string
          parts?: Message[]
      sizeEstimate?: number

  Thread:
    type: object
    properties:
      id?: string
      historyId?: string
      messages?: Message[]
    example: 123123
