#%RAML 1.0 Trait

# The contents of the file after removal of the RAML fragment identifier
# line MUST be valid structurally according to the relevant RAML
# specification.

headers:
  TestHeader : string
hi: 1