#%RAML 1.0
title: WebOfMe
mediaType: application/json

/hello:
  get:
    responses:
      200:
        body:
            properties:
                x: number
            example: |
              { "x":5, "r":2 }
