# Alternatively, if default media types have been declared at the root of
# the API, then the body declaration can consist of just the data type
# declaration or data type name describing the request body for that
# media type.

#%RAML 1.0
title: Example of request bodies
mediaType: application/json
types:
  User:
    properties:
      firstName:
      lastName:
/users:
  post:
    body:
      type: User