#%RAML 1.0
title: My API With Types

description: This RAML illustrates a type declaration that uses shortcuts to restrict its object properties.

types:
  Person:
    properties:
      name:
        type: string
      age:
        type: number
        required: false
