#%RAML 1.0
title: API
documentation:
 - title: Home
   content: |
    Also, it is not allowed to inherit from different kind of primitive
    types, for example [ number, string ].

types:
  ID:
    type: [number, string]
