#%RAML 0.8

# In the following example, calls to the /files resource must be made to "https://api-content.dropbox.com/{version}".
# All other calls in the API are made to "https://api.dropbox.com/{version}".

title: Dropbox API
version: 1
baseUri: https://{apiDomain}.dropbox.com/{version}
baseUriParameters:
  apiDomain:
    description: |
      The sub-domain at which the API is accessible. Most API calls are sent to https://api.dropbox.com
    enum: [ "api" ]
/account/info:
  displayName: Account Information
/files:
  displayName: Download files
  baseUriParameters:
    apiDomain:
      enum: [ "api-content" ]