#%RAML 0.8

# In a resource structure of resources and nested resources with their methods, the most specific baseUriParameter
# fully overrides any baseUriParameter definition made before. In the following example the resource
# /users/{userId}/image overrides the definition made in /users.

title: Users API
version: 1
baseUri: https://{apiDomain}.someapi.com
/users:
  displayName: retrieve all users
  baseUriParameters:
    apiDomain:
      enum: [ "api" ]
  /{userId}/image:
    displayName: access users pictures
    baseUriParameters:
      apiDomain:
        enum: [ "static" ]