#%RAML 1.0
title: A

types:
  DateString:
    type: string
  Year:
    type: DateString
    facets:
      maxLength: number
  AnotherYear:
    type: Year
    maxLength: 5

/search:
  get:
    queryParameters:
      y: AnotherYear
