#%RAML 1.0
title: A

# If a facet of a type is declared as required, then any subtype of
# that type MUST define a value for that facet.

types:
  CustomDate:
    type: string
    facets:
      format: string
  Year:
    type: CustomDate

/search:
  get:
    queryParameters:
      y: Year
