#%RAML 1.0
title: A

# User-defined facet names on a type MUST NOT match built-in facets on that type.

types:
  DateString:
    type: string
    facets:
      maxLength: number
  Year:
    type: DateString
    maxLength: 4

/search:
  get:
    queryParameters:
      y: Year
