# https://github.com/raml-org/raml-java-parser/issues/341
#
# No invalid test case because this tests parser's code/logic and not
# RAML spec.

#%RAML 1.0
title: API
version: v1

types:
  Num:
    type: number
    minimum: 2147483649 # max 32-bit is 2147483647
    maximum: 2147483659 # max 32-bit is 2147483647
