#%RAML 1.0
title: System Trips API

# https://github.com/raml-org/raml-java-parser/issues/444

types:
  type-from-data-type: !include data-type.raml

/trips:
  get:
    responses:
      200:
        body:
          application/json:
