#%RAML 1.0
title: API
mediaType: application/xml

types:
  Person:
    hello:

/items:
  get:
    responses:
      200:
        body:
          application/json:  # any
      204:
        body:  # application/xml
