#%RAML 1.0
title: Example with headers

/users:
  get:
    headers:
      X-Dept:
        type: array
        description: A department code to be charged.
        items:
          pattern: ^\d+\-\w+$
          example: 230-OCTO
