#%RAML 1.0 SecurityScheme

uses:
  lib: lib.raml

type: OAuth 2.0
settings:
  (lib.important): true
  authorizationUri: http://example.com
  accessTokenUri: http://example.com
  authorizationGrants: http://example.com
  scopes: http://example.com