#%RAML 1.0
title: My API With Types

/users/{id}:
  get:
    responses:
      200:
        headers:
          X-Dept:
            type: array
            description: A department code to be charged.
            items:
              pattern: ^\d+\-\w+$
              example: bbbbbbbbb