#%RAML 1.0
title: testing json schemas validation

resourceTypes:
  test:
    get:
      responses:
        201:
          body:
            application/json:
              type: !include invalid-list.json
