# The contents of the file after removal of the RAML fragment identifier
# line MUST be valid structurally according to the relevant RAML
# specification.

#%RAML 1.0 SecurityScheme

type: OAuth 2.0

settings:
  authorizationUri: http://example.com
  accessTokenUri: http://example.com
  authorizationGrants: http://example.com
  scopes: http://example.com
hi: 1