#%RAML 1.0
title: Discriminator
mediaType: application/json
uses:
  model: example-library.raml

/persons{id}:
    get:
     responses:
      200:
        body:
          type: model.Person[]
          example: # single request body example
            value: # needs to be declared since instance contains a 'value' property
              - name: A User
                userId: "111"
                kind: user
              - name: An Employee
                employeeId: "222"
                kind: administrator
            strict: false